name: google_sign_in_mocks
description: Mocks for Google Sign In.
version: 0.1.0
homepage: blog.wafrat.com
repository: https://github.com/atn832/google_sign_in_mocks

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^4.0.11
  mockito: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.0.0
  test: ^1.0.0
